#!/bin/bash
. /usr/local/lib/docker_utils/secure_docker_run.sh

echo "Container name:"
read -r CONTAINER_NAME
echo "Service port:"
read -r SERVICE_PORT
echo "Image name:"
read -r IMAGE_NAME
echo "Security sequence:"
read -r SEQUENCE
echo "Internal network name:"
read -r INTERNAL_NETWORK
echo "Public port:"
read -r PUBLIC_PORT
echo "Protocol:"
read -r PROTOCOL
echo "Public interface:"
read -r PUBLIC_INTERFACE

secure_docker_run "$CONTAINER_NAME" "$SERVICE_PORT" "$INTERNAL_NETWORK" "$IMAGE_NAME" "$PUBLIC_INTERFACE" "$PUBLIC_PORT" "$SEQUENCE" "$PROTOCOL"
