#!/bin/bash
. /usr/local/lib/docker_utils/docker_run.sh
. /usr/local/lib/knock_utils/gen_knock_rules.sh

echo "Container name:"
read -r CONTAINER_NAME
echo "Service port:"
read -r SERVICE_PORT
echo "Image name:"
read -r IMAGE_NAME
echo "Security sequence:"
read -r SEQUENCE
echo "Internal network name:"
read -r INTERNAL_NETWORK
echo "Public port:"
read -r PUBLIC_PORT
echo "Protocol:"
read -r PROTOCOL
echo "Public interface:"
read -r PUBLIC_INTERFACE

CONTAINER_IP=$(docker_run "$CONTAINER_NAME" "$SERVICE_PORT" "$INTERNAL_NETWORK" "$IMAGE_NAME")

OPEN_COMMAND="/usr/local/sbin/iptables-allow_forward_to_server $PROTOCOL $PUBLIC_INTERFACE $INTERNAL_NETWORK $PUBLIC_PORT %IP% $CONTAINER_IP $SERVICE_PORT"
CLOSE_COMMAND="/usr/local/sbin/iptables-deny_forward_to_server $PROTOCOL $PUBLIC_INTERFACE $INTERNAL_NETWORK $PUBLIC_PORT %IP% $CONTAINER_IP $SERVICE_PORT"

KNOCK_RULES=$(gen_knock_rules "$CONTAINER_NAME" "$SEQUENCE" "$OPEN_COMMAND" "$CLOSE_COMMAND")

echo "$KNOCK_RULES" >> /etc/knockd.conf

systemctl restart knockd
